# Import

In [1]:
!python -m pip install xlwt

Requirement already satisfied: xlwt in /opt/anaconda3/lib/python3.12/site-packages (1.3.0)

In [2]:
pip install openpyxl

Requirement already satisfied: openpyxl in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import random

In [4]:
!pip install xlutils xlrd xlwt

Requirement already satisfied: xlutils in /opt/anaconda3/lib/python3.12/site-packages (2.0.0)
Requirement already satisfied: xlrd in /opt/anaconda3/lib/python3.12/site-packages (2.0.2)
Requirement already satisfied: xlwt in /opt/anaconda3/lib/python3.12/site-packages (1.3.0)

# XLRD

In [5]:
import xlrd

In [6]:
xls_file = "/Users/thilak/PythonFiles/Sem 8/Data Wragling/Excel/corruption_perception_index.xls"
workbook = xlrd.open_workbook(xls_file)
sheet = workbook.sheet_by_index(0)

In [7]:
print(workbook.sheet_names())

['CPI 2013']

In [8]:
print(sheet.nrows)
print(sheet.ncols)

180
26

In [9]:
row = sheet.row_values(32)
print(row)

column = sheet.col_values(3)
print(column)

[30.0, 'Botswana', 'BWA', 616.0, 'AF', 30.0, 64.0, 7.0, 1.6, 61.0, 67.0, 60.0, 71.0, 65.0, 0.0, 62.0, 0.0, 60.0, 0.0, 60.0, 69.0, 71.0, 63.0, 0.0, 0.0, 0.0]
['', '', 'IFS Code', 128.0, 196.0, 172.0, 144.0, 142.0, 576.0, 146.0, 138.0, 193.0, 156.0, 137.0, 134.0, 176.0, 112.0, 316.0, 124.0, 532.0, 158.0, 298.0, 111.0, 178.0, 313.0, 228.0, 132.0, 362.0, 122.0, 466.0, 939.0, 453.0, 616.0, 514.0, 423.0, 182.0, '', 364.0, 436.0, 528.0, 516.0, 964.0, 184.0, 624.0, 321.0, 946.0, 961.0, 181.0, 542.0, 944.0, 718.0, 238.0, 941.0, 714.0, 684.0, 548.0, 186.0, 915.0, 666.0, 419.0, 960.0, 935.0, 728.0, 449.0, 936.0, '', 652.0, 456.0, 439.0, 962.0, 943.0, 136.0, 443.0, 968.0, 963.0, 223.0, 716.0, 965.0, 199.0, 918.0, 722.0, 744.0, 924.0, 174.0, 734.0, 748.0, 253.0, 343.0, 668.0, 948.0, 293.0, 369.0, 754.0, 676.0, 686.0, 524.0, 612.0, 911.0, 638.0, 233.0, 611.0, 534.0, 566.0, 366.0, 248.0, 921.0, 283.0, 578.0, 213.0, 218.0, 646.0, 273.0, 692.0, 644.0, '', 738.0, 469.0, 536.0, 914.0, 558.0, 582.0, 682.0, 688.0, 724.0, 537.0, 913.0, 243.0, 258.0, 742.0, 912.0, 632.0, 648.0, 446.0, 674.0, 678.0, 278.0, 564.0, 922.0, 513.0, 662.0, 336.0, 664.0, 268.0, 916.0, 544.0, 746.0, 622.0, 626.0, 429.0, 694.0, 853.0, 926.0, 656.0, 917.0, 288.0, 614.0, 634.0, 636.0, 923.0, 618.0, 518.0, 698.0, 522.0, 643.0, 299.0, 628.0, 642.0, 654.0, 263.0, 474.0, 463.0, 925.0, 927.0, '', 672.0, '', 732.0, 512.0, '', 726.0]

In [10]:
for row_idx in range(sheet.nrows):
    row_values = sheet.row_values(row_idx)
    print(row_values)

['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']
['Country Rank', 'Country / Territory', '', '', '', 'Country Rank', 'CPI 2013 Score', 'Surveys Used', 'Standard Error', '90% Confidence interval', '', 'Scores range', '', 'Data sources', '', '', '', '', '', '', '', '', '', '', '', '']
['', '', 'WB Code', 'IFS Code', 'Region', '', '', '', '', 'Lower', 'Upper', 'MIN', 'MAX', 'AFDB', 'BF (SGI)', 'BF (BTI)', 'IMD', 'ICRG', 'WB', 'WEF', 'WJP', 'EIU', 'GI', 'PERC', 'TI', 'FH']
[1.0, 'Denmark', 'DNK', 128.0, 'EU', 1.0, 91.0, 7.0, 2.2, 87.0, 95.0, 83.0, 98.0, 0.0, 97.0, 0.0, 96.0, 98.0, 0.0, 87.0, 89.0, 88.0, 83.0, 0.0, 0.0, 0.0]
[1.0, 'New Zealand', 'NZL', 196.0, 'AP', 1.0, 91.0, 7.0, 2.3, 87.0, 95.0, 83.0, 98.0, 0.0, 97.0, 0.0, 89.0, 98.0, 0.0, 96.0, 86.0, 88.0, 83.0, 0.0, 0.0, 0.0]
[3.0, 'Finland', 'FIN', 172.0, 'EU', 3.0, 89.0, 7.0, 1.7, 86.0, 92.0, 83.0, 98.0, 0.0, 89.0, 0.0, 89.0, 98.0, 0.0, 90.0, 87.0, 88.0, 83.0, 0.0, 0.0, 0.0]
[3.0, 'Sweden', 'SWE', 144.0, 'EU', 3.0, 89.0, 7.0, 2.3, 85.0, 93.0, 83.0, 98.0, 0.0, 97.0, 0.0, 83.0, 98.0, 0.0, 86.0, 89.0, 88.0, 83.0, 0.0, 0.0, 0.0]
[5.0, 'Norway', 'NOR', 142.0, 'EU', 5.0, 86.0, 7.0, 2.3, 82.0, 90.0, 80.0, 98.0, 0.0, 81.0, 0.0, 80.0, 98.0, 0.0, 85.0, 88.0, 88.0, 83.0, 0.0, 0.0, 0.0]
[5.0, 'Singapore', 'SGP', 576.0, 'AP', 5.0, 86.0, 9.0, 2.3, 82.0, 90.0, 75.0, 99.0, 0.0, 0.0, 75.0, 87.0, 79.0, 0.0, 88.0, 84.0, 88.0, 83.0, 88.0, 99.0, 0.0]
[7.0, 'Switzerland', 'CHE', 146.0, 'EU', 7.0, 85.0, 6.0, 2.5, 81.0, 89.0, 73.0, 89.0, 0.0, 89.0, 0.0, 85.0, 89.0, 0.0, 85.0, 0.0, 88.0, 73.0, 0.0, 0.0, 0.0]
[8.0, 'Netherlands', 'NLD', 138.0, 'EU', 8.0, 83.0, 7.0, 2.0, 80.0, 86.0, 73.0, 89.0, 0.0, 73.0, 0.0, 82.0, 89.0, 0.0, 82.0, 87.0, 88.0, 83.0, 0.0, 0.0, 0.0]
[9.0, 'Australia', 'AUS', 193.0, 'AP', 9.0, 81.0, 8.0, 1.5, 79.0, 83.0, 74.0, 88.0, 0.0, 81.0, 0.0, 78.0, 79.0, 0.0, 74.0, 83.0, 88.0, 83.0, 81.0, 0.0, 0.0]
[9.0, 'Canada', 'CAN', 156.0, 'AM', 9.0, 81.0, 7.0, 2.4, 77.0, 85.0, 72.0, 89.0, 0.0, 81.0, 0.0, 78.0, 89.0, 0.0, 72.0, 74.0, 88.0, 83.0, 0.0, 0.0, 0.0]
[11.0, 'Luxembourg', 'LUX', 137.0, 'EU', 11.0, 80.0, 6.0, 2.9, 75.0, 85.0, 71.0, 89.0, 0.0, 81.0, 0.0, 77.0, 89.0, 0.0, 87.0, 0.0, 71.0, 73.0, 0.0, 0.0, 0.0]
[12.0, 'Germany', 'DEU', 134.0, 'EU', 12.0, 78.0, 8.0, 2.4, 74.0, 82.0, 73.0, 89.0, 0.0, 73.0, 0.0, 79.0, 89.0, 0.0, 73.0, 75.0, 88.0, 73.0, 0.0, 74.0, 0.0]
[12.0, 'Iceland', 'ISL', 176.0, 'EU', 12.0, 78.0, 6.0, 2.8, 73.0, 83.0, 71.0, 89.0, 0.0, 73.0, 0.0, 84.0, 89.0, 0.0, 76.0, 0.0, 71.0, 73.0, 0.0, 0.0, 0.0]
[14.0, 'United Kingdom', 'GBR', 112.0, 'EU', 14.0, 76.0, 8.0, 1.3, 74.0, 78.0, 71.0, 81.0, 0.0, 73.0, 0.0, 80.0, 79.0, 0.0, 81.0, 73.0, 71.0, 73.0, 0.0, 77.0, 0.0]
[15.0, 'Barbados', 'BRB', 316.0, 'AM', 15.0, 75.0, 3.0, 7.1, 63.0, 87.0, 64.0, 88.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 64.0, 0.0, 88.0, 73.0, 0.0, 0.0, 0.0]
[15.0, 'Belgium', 'BEL', 124.0, 'EU', 15.0, 75.0, 7.0, 2.3, 71.0, 79.0, 71.0, 89.0, 0.0, 73.0, 0.0, 74.0, 89.0, 0.0, 76.0, 72.0, 71.0, 73.0, 0.0, 0.0, 0.0]
[15.0, 'Hong Kong', 'HKG', 532.0, 'AP', 15.0, 75.0, 8.0, 2.4, 71.0, 79.0, 65.0, 83.0, 0.0, 0.0, 0.0, 76.0, 69.0, 0.0, 83.0, 83.0, 71.0, 73.0, 65.0, 82.0, 0.0]
[18.0, 'Japan', 'JPN', 158.0, 'AP', 18.0, 74.0, 9.0, 2.4, 70.0, 78.0, 57.0, 81.0, 0.0, 57.0, 0.0, 79.0, 79.0, 0.0, 81.0, 78.0, 71.0, 73.0, 79.0, 73.0, 0.0]
[19.0, 'Uruguay', 'URY', 298.0, 'AM', 19.0, 73.0, 6.0, 1.4, 71.0, 75.0, 69.0, 79.0, 0.0, 0.0, 79.0, 0.0, 69.0, 0.0, 72.0, 71.0, 71.0, 73.0, 0.0, 0.0, 0.0]
[19.0, 'United States', 'USA', 111.0, 'AM', 19.0, 73.0, 9.0, 4.0, 66.0, 80.0, 50.0, 89.0, 0.0, 89.0, 0.0, 74.0, 69.0, 0.0, 64.0, 71.0, 88.0, 73.0, 76.0, 50.0, 0.0]
[21.0, 'Ireland', 'IRL', 178.0, 'EU', 21.0, 72.0, 6.0, 4.2, 65.0, 79.0, 54.0, 83.0, 0.0, 73.0, 0.0, 83.0, 69.0, 0.0, 82.0, 0.0, 54.0, 73.0, 0.0, 0.0, 0.0]
[22.0, 'Bahamas', 'BHS', 313.0, 'AM', 22.0, 71.0, 3.0, 1.0, 69.0, 73.0, 69.0, 73.0, 0.0, 0.0, 0.0, 0.0, 69.0, 0.0, 0.0, 0.0, 71.0, 73.0, 0.0, 0.0, 0.0]
[22.0, 'Chile', 'CHL', 228.0, 'AM', 22.0, 71.0, 9.0, 1.8, 68.0, 74.0, 63.0, 79.0, 0.0, 65.0, 75.0, 77.0, 79.0, 0.0, 73.0, 67.0, 71.0, 73.0, 0.0, 63.0, 0.0]
[22.0, 'France', 'FRA', 132.0, 'EU', 22.0, 71.0, 8.0, 2.4, 67.0, 75.0, 57.0, 79.0, 0.0, 57.0, 0.0, 72.0, 79.0, 0.0, 68.0, 74.0, 71.0, 73.0, 0.0, 77.0, 0.0]
[22.0, 'Saint Lucia', 'LCA', 362.0, 'AM', 22.0, 71.0, 3.0, 0.8, 70.0, 72.0, 70.0, 73.0, 0.0, 0.0, 0.0, 0.0, 0.0, 70.0, 0.0, 0.0, 71.0, 73.0, 0.0, 0.0, 0.0]
[26.0, 'Austria', 'AUT', 122.0, 'EU', 26.0, 69.0, 8.0, 3.2, 64.0, 74.0, 54.0, 81.0, 0.0, 81.0, 0.0, 64.0, 79.0, 0.0, 67.0, 71.0, 54.0, 63.0, 0.0, 74.0, 0.0]
[26.0, 'United Arab Emirates', 'ARE', 466.0, 'ME', 26.0, 69.0, 7.0, 4.7, 61.0, 77.0, 54.0, 87.0, 0.0, 0.0, 58.0, 81.0, 60.0, 0.0, 87.0, 68.0, 54.0, 73.0, 0.0, 0.0, 0.0]
[28.0, 'Estonia', 'EST', 939.0, 'EU', 28.0, 68.0, 9.0, 2.7, 64.0, 72.0, 54.0, 81.0, 0.0, 81.0, 75.0, 70.0, 60.0, 0.0, 70.0, 71.0, 54.0, 63.0, 0.0, 0.0, 66.0]
[28.0, 'Qatar', 'QAT', 453.0, 'ME', 28.0, 68.0, 6.0, 7.2, 56.0, 80.0, 45.0, 92.0, 0.0, 0.0, 45.0, 78.0, 50.0, 0.0, 92.0, 0.0, 71.0, 73.0, 0.0, 0.0, 0.0]
[30.0, 'Botswana', 'BWA', 616.0, 'AF', 30.0, 64.0, 7.0, 1.6, 61.0, 67.0, 60.0, 71.0, 65.0, 0.0, 62.0, 0.0, 60.0, 0.0, 60.0, 69.0, 71.0, 63.0, 0.0, 0.0, 0.0]
[31.0, 'Bhutan', 'BTN', 514.0, 'AP', 31.0, 63.0, 4.0, 2.6, 59.0, 67.0, 57.0, 70.0, 0.0, 0.0, 62.0, 0.0, 0.0, 70.0, 57.0, 0.0, 0.0, 63.0, 0.0, 0.0, 0.0]
[31.0, 'Cyprus', 'CYP', 423.0, 'EU', 31.0, 63.0, 5.0, 3.9, 57.0, 69.0, 49.0, 71.0, 0.0, 49.0, 0.0, 0.0, 69.0, 0.0, 61.0, 0.0, 71.0, 63.0, 0.0, 0.0, 0.0]
[33.0, 'Portugal', 'PRT', 182.0, 'EU', 33.0, 62.0, 7.0, 3.0, 57.0, 67.0, 54.0, 73.0, 0.0, 73.0, 0.0, 55.0, 60.0, 0.0, 57.0, 61.0, 54.0, 73.0, 0.0, 0.0, 0.0]
[33.0, 'Puerto Rico', 'PRI', '', 'AM', 33.0, 62.0, 3.0, 6.0, 52.0, 72.0, 51.0, 71.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 51.0, 0.0, 71.0, 63.0, 0.0, 0.0, 0.0]
[33.0, 'Saint Vincent and the Grenadines', 'VCT', 364.0, 'AM', 33.0, 62.0, 3.0, 5.6, 53.0, 71.0, 54.0, 73.0, 0.0, 0.0, 0.0, 0.0, 0.0, 58.0, 0.0, 0.0, 54.0, 73.0, 0.0, 0.0, 0.0]
[36.0, 'Israel', 'ISR', 436.0, 'ME', 36.0, 61.0, 6.0, 1.6, 58.0, 64.0, 54.0, 65.0, 0.0, 65.0, 0.0, 64.0, 60.0, 0.0, 63.0, 0.0, 54.0, 63.0, 0.0, 0.0, 0.0]
[36.0, 'Taiwan', 'TWN', 528.0, 'AP', 36.0, 61.0, 7.0, 4.3, 54.0, 68.0, 49.0, 79.0, 0.0, 0.0, 79.0, 62.0, 50.0, 0.0, 61.0, 0.0, 54.0, 73.0, 49.0, 0.0, 0.0]
[38.0, 'Brunei', 'BRN', 516.0, 'AP', 38.0, 60.0, 3.0, 10.4, 43.0, 77.0, 41.0, 76.0, 0.0, 0.0, 0.0, 0.0, 41.0, 0.0, 76.0, 0.0, 0.0, 63.0, 0.0, 0.0, 0.0]
[38.0, 'Poland', 'POL', 964.0, 'EU', 38.0, 60.0, 10.0, 2.3, 56.0, 64.0, 50.0, 73.0, 0.0, 73.0, 66.0, 55.0, 50.0, 0.0, 52.0, 65.0, 54.0, 63.0, 0.0, 63.0, 58.0]
[40.0, 'Spain', 'ESP', 184.0, 'EU', 40.0, 59.0, 7.0, 4.9, 51.0, 67.0, 41.0, 73.0, 0.0, 57.0, 0.0, 41.0, 69.0, 0.0, 46.0, 73.0, 71.0, 52.0, 0.0, 0.0, 0.0]
[41.0, 'Cape Verde', 'CPV', 624.0, 'AF', 41.0, 58.0, 4.0, 4.8, 50.0, 66.0, 49.0, 70.0, 62.0, 0.0, 0.0, 0.0, 0.0, 70.0, 49.0, 0.0, 0.0, 52.0, 0.0, 0.0, 0.0]
[41.0, 'Dominica', 'DMA', 321.0, 'AM', 41.0, 58.0, 3.0, 2.3, 54.0, 62.0, 54.0, 63.0, 0.0, 0.0, 0.0, 0.0, 0.0, 58.0, 0.0, 0.0, 54.0, 63.0, 0.0, 0.0, 0.0]
[43.0, 'Lithuania', 'LTU', 946.0, 'EU', 43.0, 57.0, 8.0, 3.8, 51.0, 63.0, 41.0, 71.0, 0.0, 65.0, 66.0, 48.0, 41.0, 0.0, 48.0, 0.0, 71.0, 63.0, 0.0, 0.0, 55.0]
[43.0, 'Slovenia', 'SVN', 961.0, 'EU', 43.0, 57.0, 9.0, 3.6, 51.0, 63.0, 36.0, 73.0, 0.0, 57.0, 62.0, 36.0, 60.0, 0.0, 47.0, 55.0, 54.0, 73.0, 0.0, 0.0, 68.0]
[45.0, 'Malta', 'MLT', 181.0, 'EU', 45.0, 56.0, 5.0, 2.4, 52.0, 60.0, 49.0, 63.0, 0.0, 49.0, 0.0, 0.0, 60.0, 0.0, 54.0, 0.0, 54.0, 63.0, 0.0, 0.0, 0.0]
[46.0, 'Korea (South)', 'KOR', 542.0, 'AP', 46.0, 55.0, 10.0, 2.4, 51.0, 59.0, 44.0, 67.0, 0.0, 57.0, 58.0, 59.0, 50.0, 0.0, 44.0, 67.0, 54.0, 52.0, 46.0, 66.0, 0.0]
[47.0, 'Hungary', 'HUN', 944.0, 'EU', 47.0, 54.0, 10.0, 3.6, 48.0, 60.0, 35.0, 71.0, 0.0, 49.0, 58.0, 35.0, 50.0, 0.0, 39.0, 65.0, 71.0, 63.0, 0.0, 57.0, 55.0]
[47.0, 'Seychelles', 'SYC', 718.0, 'AF', 47.0, 54.0, 4.0, 8.2, 41.0, 67.0, 32.0, 71.0, 32.0, 0.0, 0.0, 0.0, 0.0, 0.0, 59.0, 0.0, 71.0, 52.0, 0.0, 0.0, 0.0]
[49.0, 'Costa Rica', 'CRI', 238.0, 'AM', 49.0, 53.0, 5.0, 4.1, 46.0, 60.0, 41.0, 66.0, 0.0, 0.0, 66.0, 0.0, 41.0, 0.0, 50.0, 0.0, 54.0, 52.0, 0.0, 0.0, 0.0]
[49.0, 'Latvia', 'LVA', 941.0, 'EU', 49.0, 53.0, 8.0, 3.6, 47.0, 59.0, 41.0, 73.0, 0.0, 73.0, 53.0, 43.0, 41.0, 0.0, 49.0, 0.0, 54.0, 52.0, 0.0, 0.0, 60.0]
[49.0, 'Rwanda', 'RWA', 714.0, 'AF', 49.0, 53.0, 5.0, 5.7, 44.0, 62.0, 40.0, 74.0, 52.0, 0.0, 40.0, 0.0, 0.0, 47.0, 74.0, 0.0, 0.0, 52.0, 0.0, 0.0, 0.0]
[52.0, 'Mauritius', 'MUS', 684.0, 'AF', 52.0, 52.0, 5.0, 1.1, 50.0, 54.0, 49.0, 55.0, 55.0, 0.0, 49.0, 0.0, 0.0, 0.0, 51.0, 0.0, 54.0, 52.0, 0.0, 0.0, 0.0]
[53.0, 'Malaysia', 'MYS', 548.0, 'AP', 53.0, 50.0, 9.0, 3.4, 44.0, 56.0, 31.0, 62.0, 0.0, 0.0, 49.0, 57.0, 41.0, 0.0, 61.0, 62.0, 54.0, 42.0, 53.0, 31.0, 0.0]
[53.0, 'Turkey', 'TUR', 186.0, 'EE', 53.0, 50.0, 9.0, 2.4, 46.0, 54.0, 38.0, 58.0, 0.0, 57.0, 53.0, 58.0, 41.0, 0.0, 49.0, 48.0, 38.0, 52.0, 0.0, 57.0, 0.0]
[55.0, 'Georgia', 'GEO', 915.0, 'EE', 55.0, 49.0, 6.0, 6.9, 38.0, 60.0, 22.0, 70.0, 0.0, 0.0, 49.0, 0.0, 0.0, 47.0, 64.0, 70.0, 0.0, 22.0, 0.0, 0.0, 44.0]
[55.0, 'Lesotho', 'LSO', 666.0, 'AF', 55.0, 49.0, 5.0, 3.6, 43.0, 55.0, 42.0, 63.0, 42.0, 0.0, 45.0, 0.0, 0.0, 47.0, 47.0, 0.0, 0.0, 63.0, 0.0, 0.0, 0.0]
[57.0, 'Bahrain', 'BHR', 419.0, 'ME', 57.0, 48.0, 5.0, 5.4, 39.0, 57.0, 36.0, 65.0, 0.0, 0.0, 36.0, 0.0, 50.0, 0.0, 65.0, 0.0, 38.0, 52.0, 0.0, 0.0, 0.0]
[57.0, 'Croatia', 'HRV', 960.0, 'EU', 57.0, 48.0, 9.0, 3.3, 43.0, 53.0, 31.0, 66.0, 0.0, 49.0, 66.0, 39.0, 31.0, 0.0, 43.0, 47.0, 54.0, 52.0, 0.0, 0.0, 50.0]
[57.0, 'Czech Republic', 'CZE', 935.0, 'EU', 57.0, 48.0, 10.0, 3.0, 43.0, 53.0, 34.0, 62.0, 0.0, 49.0, 62.0, 36.0, 41.0, 0.0, 34.0, 55.0, 54.0, 52.0, 0.0, 41.0, 58.0]
[57.0, 'Namibia', 'NAM', 728.0, 'AF', 57.0, 48.0, 6.0, 3.4, 42.0, 54.0, 38.0, 63.0, 47.0, 0.0, 49.0, 0.0, 50.0, 0.0, 44.0, 0.0, 38.0, 63.0, 0.0, 0.0, 0.0]
[61.0, 'Oman', 'OMN', 449.0, 'ME', 61.0, 47.0, 5.0, 7.8, 34.0, 60.0, 28.0, 69.0, 0.0, 0.0, 28.0, 0.0, 41.0, 0.0, 69.0, 0.0, 38.0, 63.0, 0.0, 0.0, 0.0]
[61.0, 'Slovakia', 'SVK', 936.0, 'EU', 61.0, 47.0, 8.0, 4.7, 39.0, 55.0, 26.0, 62.0, 0.0, 57.0, 62.0, 29.0, 41.0, 0.0, 26.0, 0.0, 54.0, 52.0, 0.0, 0.0, 52.0]
[63.0, 'Cuba', 'CUB', '', 'AM', 63.0, 46.0, 4.0, 4.5, 39.0, 53.0, 36.0, 54.0, 0.0, 0.0, 36.0, 0.0, 41.0, 0.0, 0.0, 0.0, 54.0, 52.0, 0.0, 0.0, 0.0]
[63.0, 'Ghana', 'GHA', 652.0, 'AF', 63.0, 46.0, 9.0, 3.3, 41.0, 51.0, 28.0, 58.0, 55.0, 0.0, 49.0, 0.0, 41.0, 58.0, 40.0, 37.0, 54.0, 52.0, 0.0, 28.0, 0.0]
[63.0, 'Saudi Arabia', 'SAU', 456.0, 'ME', 63.0, 46.0, 5.0, 6.7, 35.0, 57.0, 36.0, 72.0, 0.0, 0.0, 36.0, 0.0, 41.0, 0.0, 72.0, 0.0, 38.0, 42.0, 0.0, 0.0, 0.0]
[66.0, 'Jordan', 'JOR', 439.0, 'ME', 66.0, 45.0, 7.0, 2.4, 41.0, 49.0, 36.0, 54.0, 0.0, 0.0, 36.0, 49.0, 41.0, 0.0, 44.0, 50.0, 54.0, 42.0, 0.0, 0.0, 0.0]
[67.0, 'Macedonia', 'MKD', 962.0, 'EE', 67.0, 44.0, 6.0, 5.0, 36.0, 52.0, 21.0, 55.0, 0.0, 0.0, 49.0, 0.0, 0.0, 0.0, 55.0, 48.0, 21.0, 42.0, 0.0, 0.0, 50.0]
[67.0, 'Montenegro', 'MON', 943.0, 'EE', 67.0, 44.0, 4.0, 2.2, 40.0, 48.0, 39.0, 49.0, 0.0, 0.0, 49.0, 0.0, 0.0, 0.0, 46.0, 0.0, 0.0, 42.0, 0.0, 0.0, 39.0]
[69.0, 'Italy', 'ITA', 136.0, 'EU', 69.0, 43.0, 7.0, 2.5, 39.0, 47.0, 38.0, 55.0, 0.0, 49.0, 0.0, 38.0, 41.0, 0.0, 38.0, 55.0, 38.0, 42.0, 0.0, 0.0, 0.0]
[69.0, 'Kuwait', 'KWT', 443.0, 'ME', 69.0, 43.0, 5.0, 3.9, 37.0, 49.0, 32.0, 52.0, 0.0, 0.0, 32.0, 0.0, 41.0, 0.0, 51.0, 0.0, 38.0, 52.0, 0.0, 0.0, 0.0]
[69.0, 'Romania', 'ROM', 968.0, 'EU', 69.0, 43.0, 9.0, 3.0, 38.0, 48.0, 31.0, 57.0, 0.0, 57.0, 53.0, 37.0, 31.0, 0.0, 34.0, 43.0, 38.0, 42.0, 0.0, 0.0, 50.0]
[72.0, 'Bosnia and Herzegovina', 'BIH', 963.0, 'EE', 72.0, 42.0, 7.0, 2.9, 37.0, 47.0, 35.0, 59.0, 0.0, 0.0, 40.0, 0.0, 0.0, 35.0, 59.0, 39.0, 38.0, 42.0, 0.0, 0.0, 42.0]
[72.0, 'Brazil', 'BRA', 223.0, 'AM', 72.0, 42.0, 8.0, 3.7, 36.0, 48.0, 30.0, 62.0, 0.0, 0.0, 62.0, 35.0, 41.0, 0.0, 30.0, 45.0, 38.0, 52.0, 0.0, 37.0, 0.0]
[72.0, 'Sao Tome and Principe', 'STP', 716.0, 'AF', 72.0, 42.0, 3.0, 5.0, 34.0, 50.0, 32.0, 47.0, 47.0, 0.0, 0.0, 0.0, 0.0, 47.0, 0.0, 0.0, 0.0, 32.0, 0.0, 0.0, 0.0]
[72.0, 'Serbia', 'SCG', 965.0, 'EE', 72.0, 42.0, 7.0, 3.4, 36.0, 48.0, 31.0, 53.0, 0.0, 0.0, 53.0, 0.0, 31.0, 0.0, 37.0, 35.0, 38.0, 52.0, 0.0, 0.0, 47.0]
[72.0, 'South Africa', 'ZAF', 199.0, 'AF', 72.0, 42.0, 9.0, 2.8, 37.0, 47.0, 32.0, 55.0, 55.0, 0.0, 45.0, 32.0, 41.0, 0.0, 40.0, 43.0, 54.0, 32.0, 0.0, 36.0, 0.0]
[77.0, 'Bulgaria', 'BGR', 918.0, 'EU', 77.0, 41.0, 9.0, 3.3, 36.0, 46.0, 26.0, 58.0, 0.0, 49.0, 58.0, 26.0, 31.0, 0.0, 39.0, 38.0, 38.0, 42.0, 0.0, 0.0, 50.0]
[77.0, 'Senegal', 'SEN', 722.0, 'AF', 77.0, 41.0, 9.0, 1.5, 39.0, 43.0, 33.0, 47.0, 45.0, 0.0, 45.0, 0.0, 41.0, 47.0, 38.0, 41.0, 38.0, 42.0, 0.0, 33.0, 0.0]
[77.0, 'Tunisia', 'TUN', 744.0, 'ME', 77.0, 41.0, 7.0, 1.9, 38.0, 44.0, 32.0, 46.0, 45.0, 0.0, 32.0, 0.0, 41.0, 0.0, 46.0, 45.0, 38.0, 42.0, 0.0, 0.0, 0.0]
[80.0, 'China', 'CHN', 924.0, 'AP', 80.0, 40.0, 9.0, 2.9, 35.0, 45.0, 28.0, 55.0, 0.0, 0.0, 28.0, 34.0, 31.0, 0.0, 49.0, 45.0, 38.0, 42.0, 35.0, 55.0, 0.0]
[80.0, 'Greece', 'GRC', 174.0, 'EU', 80.0, 40.0, 7.0, 4.5, 33.0, 47.0, 21.0, 57.0, 0.0, 57.0, 0.0, 40.0, 31.0, 0.0, 37.0, 49.0, 21.0, 42.0, 0.0, 0.0, 0.0]
[82.0, 'Swaziland', 'SWZ', 734.0, 'AF', 82.0, 39.0, 4.0, 1.8, 36.0, 42.0, 35.0, 42.0, 35.0, 0.0, 0.0, 0.0, 0.0, 0.0, 42.0, 0.0, 38.0, 42.0, 0.0, 0.0, 0.0]
[83.0, 'Burkina Faso', 'BFA', 748.0, 'AF', 83.0, 38.0, 7.0, 3.9, 32.0, 44.0, 20.0, 50.0, 50.0, 0.0, 32.0, 0.0, 31.0, 47.0, 20.0, 42.0, 0.0, 42.0, 0.0, 0.0, 0.0]
[83.0, 'El Salvador', 'SLV', 253.0, 'AM', 83.0, 38.0, 6.0, 2.0, 35.0, 41.0, 31.0, 45.0, 0.0, 0.0, 45.0, 0.0, 31.0, 0.0, 35.0, 38.0, 38.0, 42.0, 0.0, 0.0, 0.0]
[83.0, 'Jamaica', 'JAM', 343.0, 'AM', 83.0, 38.0, 6.0, 1.8, 35.0, 41.0, 31.0, 44.0, 0.0, 0.0, 36.0, 0.0, 31.0, 0.0, 39.0, 44.0, 38.0, 42.0, 0.0, 0.0, 0.0]
[83.0, 'Liberia', 'LBR', 668.0, 'AF', 83.0, 38.0, 7.0, 3.3, 33.0, 43.0, 28.0, 52.0, 52.0, 0.0, 45.0, 0.0, 41.0, 35.0, 30.0, 28.0, 0.0, 32.0, 0.0, 0.0, 0.0]
[83.0, 'Mongolia', 'MNG', 948.0, 'AP', 83.0, 38.0, 7.0, 2.2, 34.0, 42.0, 31.0, 47.0, 0.0, 0.0, 40.0, 0.0, 31.0, 47.0, 32.0, 33.0, 38.0, 42.0, 0.0, 0.0, 0.0]
[83.0, 'Peru', 'PER', 293.0, 'AM', 83.0, 38.0, 7.0, 2.5, 34.0, 42.0, 29.0, 49.0, 0.0, 0.0, 49.0, 38.0, 31.0, 0.0, 36.0, 29.0, 38.0, 42.0, 0.0, 0.0, 0.0]
[83.0, 'Trinidad and Tobago', 'TTO', 369.0, 'AM', 83.0, 38.0, 4.0, 5.1, 30.0, 46.0, 31.0, 52.0, 0.0, 0.0, 0.0, 0.0, 31.0, 0.0, 31.0, 0.0, 38.0, 52.0, 0.0, 0.0, 0.0]
[83.0, 'Zambia', 'ZMB', 754.0, 'AF', 83.0, 38.0, 8.0, 2.1, 35.0, 41.0, 32.0, 50.0, 50.0, 0.0, 32.0, 0.0, 41.0, 35.0, 37.0, 36.0, 38.0, 32.0, 0.0, 0.0, 0.0]
[91.0, 'Malawi', 'MWI', 676.0, 'AF', 91.0, 37.0, 8.0, 1.7, 34.0, 40.0, 31.0, 45.0, 42.0, 0.0, 45.0, 0.0, 31.0, 35.0, 35.0, 36.0, 38.0, 32.0, 0.0, 0.0, 0.0]
[91.0, 'Morocco', 'MAR', 686.0, 'ME', 91.0, 37.0, 8.0, 2.9, 32.0, 42.0, 25.0, 47.0, 47.0, 0.0, 32.0, 0.0, 31.0, 0.0, 47.0, 25.0, 38.0, 42.0, 0.0, 32.0, 0.0]
[91.0, 'Sri Lanka', 'LKA', 524.0, 'AP', 91.0, 37.0, 7.0, 2.1, 34.0, 40.0, 28.0, 44.0, 0.0, 0.0, 28.0, 0.0, 41.0, 35.0, 35.0, 44.0, 38.0, 42.0, 0.0, 0.0, 0.0]
[94.0, 'Algeria', 'DZA', 612.0, 'ME', 94.0, 36.0, 6.0, 2.8, 31.0, 41.0, 25.0, 42.0, 42.0, 0.0, 36.0, 0.0, 31.0, 0.0, 25.0, 0.0, 38.0, 42.0, 0.0, 0.0, 0.0]
[94.0, 'Armenia', 'ARM', 911.0, 'EE', 94.0, 36.0, 6.0, 3.5, 30.0, 42.0, 21.0, 47.0, 0.0, 0.0, 40.0, 0.0, 21.0, 47.0, 38.0, 0.0, 0.0, 32.0, 0.0, 0.0, 37.0]
[94.0, 'Benin', 'BEN', 638.0, 'AF', 94.0, 36.0, 6.0, 3.4, 30.0, 42.0, 25.0, 47.0, 45.0, 0.0, 32.0, 0.0, 0.0, 47.0, 25.0, 0.0, 38.0, 32.0, 0.0, 0.0, 0.0]
[94.0, 'Colombia', 'COL', 233.0, 'AM', 94.0, 36.0, 7.0, 2.0, 33.0, 39.0, 28.0, 45.0, 0.0, 0.0, 45.0, 36.0, 41.0, 0.0, 28.0, 36.0, 38.0, 32.0, 0.0, 0.0, 0.0]
[94.0, 'Djibouti', 'DJI', 611.0, 'AF', 94.0, 36.0, 3.0, 8.6, 22.0, 50.0, 23.0, 52.0, 32.0, 0.0, 0.0, 0.0, 0.0, 23.0, 0.0, 0.0, 0.0, 52.0, 0.0, 0.0, 0.0]
[94.0, 'India', 'IND', 534.0, 'AP', 94.0, 36.0, 10.0, 2.2, 32.0, 40.0, 24.0, 47.0, 0.0, 0.0, 45.0, 33.0, 41.0, 47.0, 31.0, 24.0, 38.0, 32.0, 30.0, 36.0, 0.0]
[94.0, 'Philippines', 'PHL', 566.0, 'AP', 94.0, 36.0, 9.0, 2.5, 32.0, 40.0, 21.0, 45.0, 0.0, 0.0, 45.0, 38.0, 31.0, 0.0, 41.0, 34.0, 21.0, 42.0, 31.0, 38.0, 0.0]
[94.0, 'Suriname', 'SUR', 366.0, 'AM', 94.0, 36.0, 3.0, 3.2, 31.0, 41.0, 31.0, 42.0, 0.0, 0.0, 0.0, 0.0, 31.0, 0.0, 35.0, 0.0, 0.0, 42.0, 0.0, 0.0, 0.0]
[102.0, 'Ecuador', 'ECU', 248.0, 'AM', 102.0, 35.0, 6.0, 3.6, 29.0, 41.0, 21.0, 46.0, 0.0, 0.0, 32.0, 0.0, 41.0, 0.0, 46.0, 39.0, 21.0, 32.0, 0.0, 0.0, 0.0]
[102.0, 'Moldova', 'MDA', 921.0, 'EE', 102.0, 35.0, 8.0, 2.8, 30.0, 40.0, 25.0, 47.0, 0.0, 0.0, 40.0, 0.0, 31.0, 47.0, 25.0, 25.0, 38.0, 42.0, 0.0, 0.0, 31.0]
[102.0, 'Panama', 'PAN', 283.0, 'AM', 102.0, 35.0, 6.0, 2.2, 31.0, 39.0, 28.0, 42.0, 0.0, 0.0, 28.0, 0.0, 31.0, 0.0, 39.0, 33.0, 38.0, 42.0, 0.0, 0.0, 0.0]
[102.0, 'Thailand', 'THA', 578.0, 'AP', 102.0, 35.0, 8.0, 1.2, 33.0, 37.0, 31.0, 40.0, 0.0, 0.0, 40.0, 36.0, 31.0, 0.0, 35.0, 33.0, 38.0, 32.0, 39.0, 0.0, 0.0]
[106.0, 'Argentina', 'ARG', 213.0, 'AM', 106.0, 34.0, 8.0, 2.4, 30.0, 38.0, 20.0, 40.0, 0.0, 0.0, 40.0, 34.0, 31.0, 0.0, 20.0, 40.0, 38.0, 32.0, 0.0, 38.0, 0.0]
[106.0, 'Bolivia', 'BOL', 218.0, 'AM', 106.0, 34.0, 7.0, 3.7, 28.0, 40.0, 17.0, 47.0, 0.0, 0.0, 36.0, 0.0, 31.0, 47.0, 29.0, 17.0, 38.0, 42.0, 0.0, 0.0, 0.0]
[106.0, 'Gabon', 'GAB', 646.0, 'AF', 106.0, 34.0, 5.0, 1.5, 32.0, 36.0, 31.0, 38.0, 32.0, 0.0, 0.0, 0.0, 31.0, 0.0, 38.0, 0.0, 38.0, 32.0, 0.0, 0.0, 0.0]
[106.0, 'Mexico', 'MEX', 273.0, 'AM', 106.0, 34.0, 9.0, 1.8, 31.0, 37.0, 27.0, 42.0, 0.0, 41.0, 32.0, 37.0, 31.0, 0.0, 32.0, 29.0, 38.0, 42.0, 0.0, 27.0, 0.0]
[106.0, 'Niger', 'NER', 692.0, 'AF', 106.0, 34.0, 5.0, 3.7, 28.0, 40.0, 21.0, 42.0, 42.0, 0.0, 40.0, 0.0, 21.0, 35.0, 0.0, 0.0, 0.0, 32.0, 0.0, 0.0, 0.0]
[111.0, 'Ethiopia', 'ETH', 644.0, 'AF', 111.0, 33.0, 8.0, 2.5, 29.0, 37.0, 21.0, 42.0, 42.0, 0.0, 23.0, 0.0, 21.0, 35.0, 35.0, 36.0, 38.0, 32.0, 0.0, 0.0, 0.0]
[111.0, 'Kosovo', 'LWI', '', 'EE', 111.0, 33.0, 3.0, 2.3, 29.0, 37.0, 29.0, 36.0, 0.0, 0.0, 36.0, 0.0, 0.0, 35.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 29.0]
[111.0, 'Tanzania', 'TZA', 738.0, 'AF', 111.0, 33.0, 8.0, 2.7, 29.0, 37.0, 22.0, 47.0, 47.0, 0.0, 32.0, 0.0, 31.0, 35.0, 26.0, 33.0, 38.0, 22.0, 0.0, 0.0, 0.0]
[114.0, 'Egypt', 'EGY', 469.0, 'ME', 114.0, 32.0, 7.0, 3.1, 27.0, 37.0, 17.0, 44.0, 17.0, 0.0, 32.0, 0.0, 31.0, 0.0, 30.0, 44.0, 38.0, 32.0, 0.0, 0.0, 0.0]
[114.0, 'Indonesia', 'IDN', 536.0, 'AP', 114.0, 32.0, 9.0, 3.5, 26.0, 38.0, 21.0, 50.0, 0.0, 0.0, 36.0, 42.0, 50.0, 0.0, 39.0, 23.0, 21.0, 22.0, 24.0, 33.0, 0.0]
[116.0, 'Albania', 'ALB', 914.0, 'EE', 116.0, 31.0, 7.0, 2.1, 28.0, 34.0, 23.0, 38.0, 0.0, 0.0, 32.0, 0.0, 31.0, 0.0, 23.0, 23.0, 38.0, 32.0, 0.0, 0.0, 37.0]
[116.0, 'Nepal', 'NPL', 558.0, 'AP', 116.0, 31.0, 5.0, 1.4, 29.0, 33.0, 28.0, 35.0, 0.0, 0.0, 28.0, 0.0, 0.0, 35.0, 28.0, 32.0, 0.0, 32.0, 0.0, 0.0, 0.0]
[116.0, 'Vietnam', 'VNM', 582.0, 'AP', 116.0, 31.0, 8.0, 2.6, 27.0, 35.0, 21.0, 41.0, 0.0, 0.0, 28.0, 0.0, 41.0, 35.0, 36.0, 35.0, 21.0, 22.0, 33.0, 0.0, 0.0]
[119.0, 'Mauritania', 'MRT', 682.0, 'AF', 119.0, 30.0, 5.0, 4.1, 23.0, 37.0, 21.0, 42.0, 37.0, 0.0, 28.0, 0.0, 0.0, 23.0, 21.0, 0.0, 0.0, 42.0, 0.0, 0.0, 0.0]
[119.0, 'Mozambique', 'MOZ', 688.0, 'AF', 119.0, 30.0, 7.0, 2.0, 27.0, 33.0, 23.0, 38.0, 25.0, 0.0, 28.0, 0.0, 31.0, 35.0, 23.0, 0.0, 38.0, 32.0, 0.0, 0.0, 0.0]
[119.0, 'Sierra Leone', 'SLE', 724.0, 'AF', 119.0, 30.0, 8.0, 2.4, 26.0, 34.0, 21.0, 40.0, 40.0, 0.0, 36.0, 0.0, 21.0, 35.0, 29.0, 28.0, 21.0, 32.0, 0.0, 0.0, 0.0]
[119.0, 'Timor-Leste', 'TLS', 537.0, 'AP', 119.0, 30.0, 3.0, 3.2, 25.0, 35.0, 23.0, 34.0, 0.0, 0.0, 0.0, 0.0, 0.0, 23.0, 34.0, 0.0, 0.0, 32.0, 0.0, 0.0, 0.0]
[123.0, 'Belarus', 'BLR', 913.0, 'EE', 123.0, 29.0, 5.0, 4.0, 22.0, 36.0, 21.0, 43.0, 0.0, 0.0, 32.0, 0.0, 21.0, 0.0, 0.0, 43.0, 0.0, 22.0, 0.0, 0.0, 26.0]

In [11]:
headers = sheet.row_values(0)
data = []

for r in range(1, sheet.nrows):
    row = sheet.row_values(r)
    data.append(dict(zip(headers, row)))

print(data)

[{'': ''}, {'': 'FH'}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 66.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 58.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 55.0}, {'': 68.0}, {'': 0.0}, {'': 0.0}, {'': 55.0}, {'': 0.0}, {'': 0.0}, {'': 60.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 44.0}, {'': 0.0}, {'': 0.0}, {'': 50.0}, {'': 58.0}, {'': 0.0}, {'': 0.0}, {'': 52.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 50.0}, {'': 39.0}, {'': 0.0}, {'': 0.0}, {'': 50.0}, {'': 42.0}, {'': 0.0}, {'': 0.0}, {'': 47.0}, {'': 0.0}, {'': 50.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 37.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 31.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 29.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 37.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 26.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 21.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 23.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 23.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 29.0}, {'': 0.0}, {'': 26.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 26.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 21.0}, {'': 21.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}, {'': 0.0}]

In [12]:
# Select random row and column indices
random_rows_idx = random.sample(range(sheet.nrows), 5)
random_cols_idx = random.sample(range(sheet.ncols), 3)

for r in random_rows_idx:
    row_data = [sheet.cell_value(r, c) for c in random_cols_idx]
    print(f"Row {r}, Columns {random_cols_idx}: {row_data}")

Row 130, Columns [23, 2, 21]: [0.0, 'COM', 0.0]
Row 23, Columns [23, 2, 21]: [0.0, 'IRL', 54.0]
Row 19, Columns [23, 2, 21]: [65.0, 'HKG', 71.0]
Row 124, Columns [23, 2, 21]: [0.0, 'TLS', 0.0]
Row 45, Columns [23, 2, 21]: [0.0, 'LTU', 71.0]

In [13]:
xls_file = "/Users/thilak/PythonFiles/Sem 8/Data Wragling/Excel/data-text (1).xls"
workbook = xlrd.open_workbook(xls_file)
sheet = workbook.sheet_by_index(0)

sheet_by_name = workbook.sheet_by_name(workbook.sheet_names()[0])
print(f"Sheet name: {sheet_by_name.name}",'\n')

cell_value = sheet.cell_value(rowx=1, colx=0)
print(f"Cell (1,0): {cell_value}",'\n')

#(0=empty, 1=text, 2=number, 3=date, 4=boolean, 5=error)
cell_type = sheet.cell_type(rowx=1, colx=0)
print(f"Cell type: {cell_type}",'\n')

cell = sheet.cell(rowx=1, colx=0)
print(f"Cell object: {cell}, Value: {cell.value}, Type: {cell.ctype}",'\n')

row_slice = sheet.row_slice(rowx=1, start_colx=0, end_colx=3)
print(f"Row slice: {[c.value for c in row_slice]}",'\n')

col_slice = sheet.col_slice(colx=0, start_rowx=0, end_rowx=5)
print(f"Column slice: {[c.value for c in col_slice]}")

Sheet name: data-text

Cell (1,0): Life expectancy at birth (years)

Cell type: 1

Cell object: text:'Life expectancy at birth (years)', Value: Life expectancy at birth (years), Type: 1

Row slice: ['Life expectancy at birth (years)', 'Published', 1990.0]

Column slice: ['Indicator', 'Life expectancy at birth (years)', 'Life expectancy at birth (years)', 'Life expectancy at age 60 (years)', 'Life expectancy at age 60 (years)']

# PYXL

In [14]:
from openpyxl import load_workbook, Workbook
woorkbook = load_workbook("/Users/thilak/PythonFiles/Sem 8/Data Wragling/Excel/SOWC 2014 Stat Tables_Table 9.xlsx")
sheet = woorkbook.active

In [15]:
# Read Data in PYXL
for row in sheet.iter_rows(min_row=1, max_row=10, values_only=True):
    print(row)

('Overview', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None)
('This reference guide presents the most recent key statistics on child survival, development and protection for the world’s countries, areas and regions. The statistical tables in this volume support UNICEF’s focus on progress and results towards internationally agreed-upon goals and compacts relating to children’s rights and development. UNICEF is the lead agency responsible for monitoring the child-related goals of the Millennium Declaration as well as the Millennium Development Goals (MDGs) and indicators. UNICEF is also a key partner in the United Nations’ work on monitoring these targets and indicators. Efforts have been made to maximize the comparability of statistics across countries and time. Nevertheless, data used at the country level may differ in terms of the methods used to collect data or arrive at estimates, and in terms of the populations covered. Furthermore, data presented here are subject to evolving methodologies, revisions of time series data (e.g., immunization, maternal mortality ratios) and changing regional classifications. Also, data comparable from one year to the next are unavailable for some indicators. It is therefore not advisable to compare data from consecutive editions of The State of the World’s Children. The numbers presented in this reference guide are available online at <www.unicef.org/sowc2014> and via the UNICEF global statistical databases at <www.childinfo.org>. Please refer to these websites for the latest tables and for any updates or corrigenda subsequent to printing.', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None)
('General note on the data', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None)
('Data presented in the following statistical tables are derived from the UNICEF global databases and are accompanied by definitions, sources and, where necessary, additional footnotes. The tables draw on inter-agency estimates and nationally representative household surveys such as Multiple Indicator Cluster Surveys (MICS) and Demographic and Health Surveys (DHS). In addition, data from other United Nations organizations have been used. Data presented in this year’s statistical tables generally reflect information available as of August 2013. More detailed information on methodology and data sources is available at <www.childinfo.org>. This volume includes the latest population estimates and projections from World Population Prospects: The 2012 revision and World Urbanization Prospects: The 2011 revision (United Nations Department of Economic and Social Affairs, Population Division). Data quality is likely to be adversely affected for countries that have recently suffered disasters, especially where basic country infrastructure has been fragmented or where major population movements have occurred. Multiple Indicator Cluster Surveys (MICS): UNICEF supports countries in collecting reliable and globally mapped data through MICS. Since 1995, about 250 surveys have been conducted in more than 100 countries and areas. The fifth round of MICS, involving over 40 surveys to date, is under way. MICS are among the largest sources of data for monitoring progress towards internationally agreed-upon development goals for children, including the MDGs. More information is available at <www.childinfo.org/mics.html>.', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None)
(None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None)
('Regional classification', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None)
('Averages presented at the end of each of the 14 statistical tables are calculated using data from countries and areas as classified below.', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None)
('Sub-Saharan Africa', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None)
('Eastern and Southern Africa; West and Central Africa; Djibouti; Sudan', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None)
('Eastern and Southern Africa', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None)

In [16]:
head = [cell.value for cell in sheet[1]]
print(head)

['Overview', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]

In [17]:
# Write in PYXL
sheet.append(["Country", "Child Labor Total", "Child Marriage by 18"])
sheet.append(["Zimbabwe", 2005.2, 32.5])

woorkbook.save("new.xlsx")
print("Data written")

Data written

In [18]:
print(sheet.max_row)
print(sheet.max_column)

134
24

In [19]:
max_row = sheet.max_row
max_col = sheet.max_column

random_rows_idx = random.sample(range(1, max_row + 1), 5)
random_cols_idx = random.sample(range(1, max_col + 1), 3)

for r in random_rows_idx:
    row_data = [sheet.cell(row=r, column=c).value for c in random_cols_idx]
    print(f"Row {r}, Columns {random_cols_idx}: {row_data}")

Row 130, Columns [12, 6, 14]: [None, None, None]
Row 108, Columns [12, 6, 14]: [None, None, None]
Row 74, Columns [12, 6, 14]: [None, None, None]
Row 85, Columns [12, 6, 14]: [None, None, None]
Row 93, Columns [12, 6, 14]: [None, None, None]

In [20]:
from openpyxl.styles import Font, Alignment, Border, Side, PatternFill
from openpyxl.utils import get_column_letter, column_index_from_string

workbook = load_workbook("/Users/thilak/PythonFiles/Sem 8/Data Wragling/Excel/SOWC 2014 Stat Tables_Table 9.xlsx")
sheet = workbook.active

In [21]:
cell_A1 = sheet['A1']
print(f"Cell A1: {cell_A1.value}")

cell = sheet.cell(row=1, column=1)
print(f"Cell (1,1): {cell.value}")

col_letter = get_column_letter(5)
print(f"Column 5 letter: {col_letter}")  

col_index = column_index_from_string('E')
print(f"Column E index: {col_index}")  


for col in sheet.iter_cols(min_row=1, max_row=3, min_col=1, max_col=3, values_only=True):
    print(f"Column: {col}")

print(f"All sheets: {workbook.sheetnames}")

new_sheet = workbook.create_sheet("NewSheet")

print(f"Dimensions: {sheet.dimensions}")

Cell A1: Overview
Cell (1,1): Overview
Column 5 letter: E
Column E index: 5
Column: ('Overview', 'This reference guide presents the most recent key statistics on child survival, development and protection for the world’s countries, areas and regions. The statistical tables in this volume support UNICEF’s focus on progress and results towards internationally agreed-upon goals and compacts relating to children’s rights and development. UNICEF is the lead agency responsible for monitoring the child-related goals of the Millennium Declaration as well as the Millennium Development Goals (MDGs) and indicators. UNICEF is also a key partner in the United Nations’ work on monitoring these targets and indicators. Efforts have been made to maximize the comparability of statistics across countries and time. Nevertheless, data used at the country level may differ in terms of the methods used to collect data or arrive at estimates, and in terms of the populations covered. Furthermore, data presented here are subject to evolving methodologies, revisions of time series data (e.g., immunization, maternal mortality ratios) and changing regional classifications. Also, data comparable from one year to the next are unavailable for some indicators. It is therefore not advisable to compare data from consecutive editions of The State of the World’s Children. The numbers presented in this reference guide are available online at <www.unicef.org/sowc2014> and via the UNICEF global statistical databases at <www.childinfo.org>. Please refer to these websites for the latest tables and for any updates or corrigenda subsequent to printing.', 'General note on the data')
Column: (None, None, None)
Column: (None, None, None)
All sheets: ['Data Notes', 'Table 9 ']
Dimensions: A1:X132

In [22]:
wb_new = Workbook()
ws_new = wb_new.active

ws_new['A1'] = "Bold Red Text"
ws_new['A1'].font = Font(bold=True, color="FF0000", size=14)

ws_new['A2'] = "Centered Text"
ws_new['A2'].alignment = Alignment(horizontal='center', vertical='center')

ws_new['A3'] = "Yellow Background"
ws_new['A3'].fill = PatternFill(start_color="FFFF00", end_color="FFFF00", fill_type="solid")
thin_border = Border(left=Side(style='thin'),right=Side(style='thin'),top=Side(style='thin'),bottom=Side(style='thin'))
ws_new['A4'] = "Bordered Cell"
ws_new['A4'].border = thin_border


ws_new.merge_cells('B1:D1')
ws_new['B1'] = "Merged Cell"

ws_new.column_dimensions['A'].width = 25
ws_new.row_dimensions[1].height = 30

ws_new['E1'] = 10
ws_new['E2'] = 20
ws_new['E3'] = '=SUM(E1:E2)'
ws_new['F1'] = "Click Here"
ws_new['F1'].hyperlink = "https://www.google.com"

ws_new.insert_rows(2)  
ws_new.insert_cols(2)  
wb_new.save("/Users/thilak/PythonFiles/Sem 8/Data Wragling/Excel/styled_output.xlsx")
print("Styled workbook saved!")

Styled workbook saved!

# Pandas

In [23]:
import pandas as pd
df = pd.read_excel("/Users/thilak/PythonFiles/Sem 8/Data Wragling/Excel/data-text.xlsx")

In [24]:
df

,Indicator,PUBLISH STATES,Year,WHO region,World Bank income group,Country,Sex,Display Value,Numeric,Low,High,Comments
0,Life expectancy at birth (years),Published,1990,Europe,High-income,Andorra,Both sexes,77,77,NaN,NaN,NaN
1,Life expectancy at birth (years),Published,2000,Europe,High-income,Andorra,Both sexes,80,80,NaN,NaN,NaN
2,Life expectancy at age 60 (years),Published,2012,Europe,High-income,Andorra,Female,28,28,NaN,NaN,NaN
3,Life expectancy at age 60 (years),Published,2000,Europe,High-income,Andorra,Both sexes,23,23,NaN,NaN,NaN
4,Life expectancy at birth (years),Published,2012,Eastern Mediterranean,High-income,United Arab Emirates,Female,78,78,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
4656,Sample Indicator,Published,2024,Europe,High-income,Sample Country,Both sexes,99,99,NaN,NaN,NaN
4657,Sample Indicator,Published,2024,Europe,High-income,Sample Country,Both sexes,99,99,NaN,NaN,NaN
4658,Sample Indicator,Published,2024,Europe,High-income,Sample Country,Both sexes,99,99,NaN,NaN,NaN
4659,Sample Indicator,Published,2024,Europe,High-income,Sample Country,Both sexes,99,99,NaN,NaN,NaN
4660,Sample Indicator,Published,2024,Europe,High-income,Sample Country,Both sexes,99,99,NaN,NaN,NaN

In [25]:
df.head(3)

,Indicator,PUBLISH STATES,Year,WHO region,World Bank income group,Country,Sex,Display Value,Numeric,Low,High,Comments
0,Life expectancy at birth (years),Published,1990,Europe,High-income,Andorra,Both sexes,77,77,NaN,NaN,NaN
1,Life expectancy at birth (years),Published,2000,Europe,High-income,Andorra,Both sexes,80,80,NaN,NaN,NaN
2,Life expectancy at age 60 (years),Published,2012,Europe,High-income,Andorra,Female,28,28,NaN,NaN,NaN

In [26]:
df.columns

Index(['Indicator', 'PUBLISH STATES', 'Year', 'WHO region',
       'World Bank income group', 'Country', 'Sex', 'Display Value', 'Numeric',
       'Low', 'High', 'Comments'],
      dtype='object')

In [27]:
df.describe()

              Year  Display Value      Numeric  Low  High  Comments
count  4661.000000    4661.000000  4661.000000  0.0   0.0       0.0
mean   2002.023600      47.250161    47.250161  NaN   NaN       NaN
std       8.686448      23.890677    23.890677  NaN   NaN       NaN
min    1990.000000      11.000000    11.000000  NaN   NaN       NaN
25%    2000.000000      20.000000    20.000000  NaN   NaN       NaN
50%    2000.000000      55.000000    55.000000  NaN   NaN       NaN
75%    2012.000000      68.000000    68.000000  NaN   NaN       NaN
max    2024.000000      99.000000    99.000000  NaN   NaN       NaN

In [28]:
# Write in xlsx
df = pd.read_excel("/Users/thilak/PythonFiles/Sem 8/Data Wragling/Excel/data-text.xlsx")

new_row = {
    'Indicator': 'Sample Indicator',
    'PUBLISH STATES': 'Published',
    'Year': 2024,
    'WHO region': 'Europe',
    'World Bank income group': 'High-income',
    'Country': 'Sample Country',
    'Sex': 'Both sexes',
    'Display Value': 99,
    'Numeric': 99,
    'Low': None,
    'High': None,
    'Comments': None
}

new_row_df = pd.DataFrame([new_row])
df = pd.concat([df, new_row_df], ignore_index=True)

df.to_excel("/Users/thilak/PythonFiles/Sem 8/Data Wragling/Excel/data-text.xlsx", index=False)

print("Row added successfully!")

Row added successfully!

In [29]:

random_row = df.sample(n=1).iloc[0]
print(random_row)

random_rows = df.sample(n=5)
print(random_rows)


import random
random_index = random.randint(0, len(df) - 1)
random_row = df.iloc[random_index]
print(random_row)

Indicator                  Life expectancy at age 60 (years)
PUBLISH STATES                                     Published
Year                                                    2012
WHO region                                            Europe
World Bank income group                  Upper-middle-income
Country                                               Turkey
Sex                                                   Female
Display Value                                             23
Numeric                                                   23
Low                                                      NaN
High                                                     NaN
Comments                                                 NaN
Name: 2584, dtype: object
                                            Indicator PUBLISH STATES  Year  \
3335                 Life expectancy at birth (years)      Published  2012
3202                 Life expectancy at birth (years)      Published  2000
1429                Life expectancy at age 60 (years)      Published  2000
1907                 Life expectancy at birth (years)      Published  1990
2308  Healthy life expectancy (HALE) at birth (years)      Published  2000

           WHO region World Bank income group     Country         Sex  \
3335           Europe     Upper-middle-income      Serbia  Both sexes
3202  South-East Asia     Lower-middle-income    Maldives  Both sexes
1429         Americas              Low-income       Haiti      Female
1907           Europe              Low-income  Tajikistan  Both sexes
2308           Europe             High-income      Greece  Both sexes

      Display Value  Numeric  Low High Comments
3335             75       75  NaN  NaN      NaN
3202             68       68  NaN  NaN      NaN
1429             16       16  NaN  NaN      NaN
1907             64       64  NaN  NaN      NaN
2308             69       69  NaN  NaN      NaN
Indicator                  Life expectancy at age 60 (years)
PUBLISH STATES                                     Published
Year                                                    2012
WHO region                                            Africa
World Bank income group                  Lower-middle-income
Country                                              Nigeria
Sex                                                     Male
Display Value                                             15
Numeric                                                   15
Low                                                      NaN
High                                                     NaN
Comments                                                 NaN
Name: 1600, dtype: object

In [30]:
filtered_df = df[df['Year'] == 2024]
print(filtered_df)

# 17. Multiple conditions
filtered_df = df[(df['Year'] >= 2020) & (df['Country'] == 'Sample Country')]

# 18. Filter using query
filtered_df = df.query("Year >= 2020")

# 19. Filter using isin
filtered_df = df[df['Country'].isin(['India', 'USA', 'UK'])]

             Indicator PUBLISH STATES  Year WHO region  \
4656  Sample Indicator      Published  2024     Europe
4657  Sample Indicator      Published  2024     Europe
4658  Sample Indicator      Published  2024     Europe
4659  Sample Indicator      Published  2024     Europe
4660  Sample Indicator      Published  2024     Europe
4661  Sample Indicator      Published  2024     Europe

     World Bank income group         Country         Sex  Display Value  \
4656             High-income  Sample Country  Both sexes             99
4657             High-income  Sample Country  Both sexes             99
4658             High-income  Sample Country  Both sexes             99
4659             High-income  Sample Country  Both sexes             99
4660             High-income  Sample Country  Both sexes             99
4661             High-income  Sample Country  Both sexes             99

      Numeric   Low  High Comments
4656       99   NaN   NaN      NaN
4657       99   NaN   NaN      NaN
4658       99   NaN   NaN      NaN
4659       99   NaN   NaN      NaN
4660       99   NaN   NaN      NaN
4661       99  None  None     None

In [31]:
df['New_Column'] = df['Numeric'] * 2

df_renamed = df.rename(columns={'Country': 'Nation', 'Year': 'Yr'})

df_dropped = df.drop(columns=['Comments'])
df_dropped = df.drop(index=[0, 1])

df_filled = df.fillna(0)
df_filled = df.fillna({'Low': 0, 'High': 100})

df_clean = df.dropna()
df_clean = df.dropna(subset=['Numeric'])

/var/folders/53/hrzqkfv52rq1kglt63668d5h0000gn/T/ipykernel_5937/2512278513.py:8: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_filled = df.fillna(0)
/var/folders/53/hrzqkfv52rq1kglt63668d5h0000gn/T/ipykernel_5937/2512278513.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_filled = df.fillna({'Low': 0, 'High': 100})

In [32]:
df_clean

,Indicator,PUBLISH STATES,Year,WHO region,World Bank income group,Country,Sex,Display Value,Numeric,Low,High,Comments,New_Column
0,Life expectancy at birth (years),Published,1990,Europe,High-income,Andorra,Both sexes,77,77,NaN,NaN,NaN,154
1,Life expectancy at birth (years),Published,2000,Europe,High-income,Andorra,Both sexes,80,80,NaN,NaN,NaN,160
2,Life expectancy at age 60 (years),Published,2012,Europe,High-income,Andorra,Female,28,28,NaN,NaN,NaN,56
3,Life expectancy at age 60 (years),Published,2000,Europe,High-income,Andorra,Both sexes,23,23,NaN,NaN,NaN,46
4,Life expectancy at birth (years),Published,2012,Eastern Mediterranean,High-income,United Arab Emirates,Female,78,78,NaN,NaN,NaN,156
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4657,Sample Indicator,Published,2024,Europe,High-income,Sample Country,Both sexes,99,99,NaN,NaN,NaN,198
4658,Sample Indicator,Published,2024,Europe,High-income,Sample Country,Both sexes,99,99,NaN,NaN,NaN,198
4659,Sample Indicator,Published,2024,Europe,High-income,Sample Country,Both sexes,99,99,NaN,NaN,NaN,198
4660,Sample Indicator,Published,2024,Europe,High-income,Sample Country,Both sexes,99,99,NaN,NaN,NaN,198
4661,Sample Indicator,Published,2024,Europe,High-income,Sample Country,Both sexes,99,99,None,None,None,198

# xlutils

In [33]:
import xlrd
import xlwt
from xlutils.copy import copy

In [34]:
xls_file = "/Users/thilak/PythonFiles/Sem 8/Data Wragling/Excel/data-text (1).xls"
workbook = xlrd.open_workbook(xls_file)
sheet = workbook.sheet_by_index(0)

print("Reading Data")
print(f"Sheet name: {sheet.name}")
print(f"Rows: {sheet.nrows}, Columns: {sheet.ncols}",'\n')


for row_idx in range(min(5, sheet.nrows)):
    print(sheet.row_values(row_idx))

Reading Data
Sheet name: data-text
Rows: 4657, Columns: 12

['Indicator', 'PUBLISH STATES', 'Year', 'WHO region', 'World Bank income group', 'Country', 'Sex', 'Display Value', 'Numeric', 'Low', 'High', 'Comments']
['Life expectancy at birth (years)', 'Published', 1990.0, 'Europe', 'High-income', 'Andorra', 'Both sexes', 77.0, 77.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 2000.0, 'Europe', 'High-income', 'Andorra', 'Both sexes', 80.0, 80.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 2012.0, 'Europe', 'High-income', 'Andorra', 'Female', 28.0, 28.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 2000.0, 'Europe', 'High-income', 'Andorra', 'Both sexes', 23.0, 23.0, '', '', '']

In [35]:
# WRITE with xlwt
print("Write")
new_workbook = xlwt.Workbook()
new_sheet = new_workbook.add_sheet("MySheet")


headers = ["Name", "Age", "City"]
for col, header in enumerate(headers):
    new_sheet.write(0, col, header)


data = [["Haris", 25, "Mumbai"],["Yuvan", 30, "Delhi"],["Sai", 18, "Bangalore"]]

for row_idx, row_data in enumerate(data, start=1):
    for col_idx, value in enumerate(row_data):
        new_sheet.write(row_idx, col_idx, value)

new_workbook.save("/Users/thilak/PythonFiles/Sem 8/Data Wragling/Excel/xlwt_output.xls")
print("New file saved: xlwt_output.xls")

Write
New file saved: xlwt_output.xls

# Aspose

In [36]:
pip install aspose-cells-python

Requirement already satisfied: aspose-cells-python in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (25.11.0)
Note: you may need to restart the kernel to use updated packages.

In [37]:
from aspose.cells import Workbook

wb = Workbook("/Users/thilak/PythonFiles/Sem 8/Data Wragling/Excel/data-text.xlsx")
sheet = wb.worksheets[0]

# Write data
sheet.cells.get("A1").put_value("Total")
sheet.cells.get("B1").put_value(1250)

# Save in any format
wb.save("output.pdf")

# XLSWritter

In [38]:
import pandas as pd
import xlsxwriter

out_path = "/Users/thilak/PythonFiles/Sem 8/Data Wragling/Excel/xlsxwriter_output.xlsx"

# Write with formats and chart
with xlsxwriter.Workbook(out_path) as wb:
    ws = wb.add_worksheet("Report")
    header_fmt = wb.add_format({"bold": True, "bg_color": "#ADD8E6", "border": 1})
    num_fmt = wb.add_format({"num_format": "0.00", "border": 1})
    ws.write_row("A1", ["Name", "Score"], header_fmt)
    data = [("Alice", 85), ("Bob", 72), ("Charlie", 90), ("David", 65)]
    for r, (name, score) in enumerate(data, start=1):
        ws.write(r, 0, name)
        ws.write(r, 1, score, num_fmt)

    ws.conditional_format("B2:B5", {"type": "3_color_scale"})
    # Chart
    chart = wb.add_chart({"type": "column"})
    chart.add_series({"name": "Scores", "categories": "=Report!$A$2:$A$5", "values": "=Report!$B$2:$B$5"})
    ws.insert_chart("D2", chart)

df = pd.read_excel(out_path, sheet_name="Report")
print(df)

      Name  Score
0    Alice     85
1      Bob     72
2  Charlie     90
3    David     65

# Pyexcelerate

In [39]:
pip install pyexcelerate

Requirement already satisfied: pyexcelerate in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (0.13.0)
Requirement already satisfied: Jinja2 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pyexcelerate) (3.1.4)
Requirement already satisfied: six>=1.4.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pyexcelerate) (1.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from Jinja2->pyexcelerate) (2.1.5)
Note: you may need to restart the kernel to use updated packages.

In [40]:
from pyexcelerate import Workbook
import pandas as pd

out_path = "/Users/thilak/PythonFiles/Sem 8/Data Wragling/Excel/pyexcelerate_output.xlsx"

data = [
    ["Name", "Score", "Twice"],
    ["Alice", 85, "=B2*2"],
    ["Bob", 72, "=B3*2"],
    ["Charlie", 90, "=B4*2"],
    ["David", 65, "=B5*2"],
]

wb = Workbook()
wb.new_sheet("FastSheet", data=data)
wb.save(out_path)

df = pd.read_excel(out_path)
print(df)

      Name  Score  Twice
0    Alice     85    NaN
1      Bob     72    NaN
2  Charlie     90    NaN
3    David     65    NaN

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/openpyxl/styles/stylesheet.py:232: UserWarning: Workbook contains no stylesheet, using openpyxl's defaults
  warn("Workbook contains no stylesheet, using openpyxl's defaults")

# ODFPY

In [41]:
pip install odfpy

Requirement already satisfied: odfpy in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (1.4.1)
Requirement already satisfied: defusedxml in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from odfpy) (0.7.1)
Note: you may need to restart the kernel to use updated packages.

In [42]:
from odf.opendocument import OpenDocumentSpreadsheet
from odf.table import Table, TableRow, TableCell
from odf.text import P

doc = OpenDocumentSpreadsheet()
table = Table(name="Sheet1")
row = TableRow()
row.addElement(TableCell(value=42))
row.addElement(TableCell())
row.addElement(TableCell())
table.addElement(row)
doc.spreadsheet.addElement(table)
doc.save("/Users/thilak/PythonFiles/Sem 8/Data Wragling/Excel/odfpy_output.ods")

# Plotly

In [43]:
import plotly.express as px

df = px.data.tips()   # preloaded dataset
fig = px.bar(df, x="day", y="total_bill", title="Total Bill by Day")
fig.show()

# Calamine

In [44]:
pip install python_calamine

Requirement already satisfied: python_calamine in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (0.6.1)
Note: you may need to restart the kernel to use updated packages.

In [45]:
from python_calamine import CalamineWorkbook
wb = CalamineWorkbook.from_path("/Users/thilak/PythonFiles/Sem 8/Data Wragling/Excel/data-text.xlsx")

sheet_names = wb.sheet_names
print("Sheet names:", sheet_names)
data = wb.get_sheet_by_name(sheet_names[0]).to_python()

for row in data:
    print(row)

Sheet names: ['Sheet1']
['Indicator', 'PUBLISH STATES', 'Year', 'WHO region', 'World Bank income group', 'Country', 'Sex', 'Display Value', 'Numeric', 'Low', 'High', 'Comments']
['Life expectancy at birth (years)', 'Published', 1990.0, 'Europe', 'High-income', 'Andorra', 'Both sexes', 77.0, 77.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 2000.0, 'Europe', 'High-income', 'Andorra', 'Both sexes', 80.0, 80.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 2012.0, 'Europe', 'High-income', 'Andorra', 'Female', 28.0, 28.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 2000.0, 'Europe', 'High-income', 'Andorra', 'Both sexes', 23.0, 23.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 2012.0, 'Eastern Mediterranean', 'High-income', 'United Arab Emirates', 'Female', 78.0, 78.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 2000.0, 'Americas', 'High-income', 'Antigua and Barbuda', 'Male', 72.0, 72.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 1990.0, 'Americas', 'High-income', 'Antigua and Barbuda', 'Male', 17.0, 17.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 2012.0, 'Americas', 'High-income', 'Antigua and Barbuda', 'Both sexes', 22.0, 22.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 2012.0, 'Western Pacific', 'High-income', 'Australia', 'Male', 81.0, 81.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 2000.0, 'Western Pacific', 'High-income', 'Australia', 'Both sexes', 80.0, 80.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 2012.0, 'Western Pacific', 'High-income', 'Australia', 'Both sexes', 83.0, 83.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 2012.0, 'Europe', 'High-income', 'Austria', 'Female', 83.0, 83.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 2012.0, 'Europe', 'High-income', 'Austria', 'Female', 25.0, 25.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 2012.0, 'Europe', 'High-income', 'Belgium', 'Female', 83.0, 83.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 2000.0, 'Eastern Mediterranean', 'High-income', 'Bahrain', 'Male', 73.0, 73.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 1990.0, 'Eastern Mediterranean', 'High-income', 'Bahrain', 'Female', 74.0, 74.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 1990.0, 'Eastern Mediterranean', 'High-income', 'Bahrain', 'Male', 17.0, 17.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 2012.0, 'Americas', 'High-income', 'Bahamas', 'Male', 72.0, 72.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 2000.0, 'Americas', 'High-income', 'Bahamas', 'Both sexes', 21.0, 21.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 1990.0, 'Americas', 'High-income', 'Barbados', 'Male', 71.0, 71.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 2012.0, 'Americas', 'High-income', 'Barbados', 'Female', 25.0, 25.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 2012.0, 'Americas', 'High-income', 'Barbados', 'Both sexes', 23.0, 23.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 1990.0, 'Western Pacific', 'High-income', 'Brunei Darussalam', 'Female', 20.0, 20.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 2000.0, 'Western Pacific', 'High-income', 'Brunei Darussalam', 'Female', 22.0, 22.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 2012.0, 'Western Pacific', 'High-income', 'Brunei Darussalam', 'Female', 21.0, 21.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 2000.0, 'Americas', 'High-income', 'Canada', 'Female', 82.0, 82.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 2000.0, 'Americas', 'High-income', 'Canada', 'Male', 21.0, 21.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 1990.0, 'Americas', 'High-income', 'Canada', 'Female', 24.0, 24.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 1990.0, 'Europe', 'High-income', 'Switzerland', 'Male', 74.0, 74.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 2012.0, 'Europe', 'High-income', 'Switzerland', 'Both sexes', 83.0, 83.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 2000.0, 'Europe', 'High-income', 'Switzerland', 'Both sexes', 23.0, 23.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 2012.0, 'Western Pacific', 'High-income', 'Cook Islands', 'Both sexes', 76.0, 76.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 2012.0, 'Western Pacific', 'High-income', 'Cook Islands', 'Female', 22.0, 22.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 2000.0, 'Western Pacific', 'High-income', 'Cook Islands', 'Both sexes', 18.0, 18.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 2000.0, 'Europe', 'High-income', 'Cyprus', 'Female', 79.0, 79.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 2000.0, 'Europe', 'High-income', 'Cyprus', 'Both sexes', 77.0, 77.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 2000.0, 'Europe', 'High-income', 'Cyprus', 'Female', 22.0, 22.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 2012.0, 'Europe', 'High-income', 'Cyprus', 'Female', 26.0, 26.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 2012.0, 'Europe', 'High-income', 'Czech Republic', 'Male', 75.0, 75.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 1990.0, 'Europe', 'High-income', 'Czech Republic', 'Female', 75.0, 75.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 1990.0, 'Europe', 'High-income', 'Germany', 'Female', 79.0, 79.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 1990.0, 'Europe', 'High-income', 'Germany', 'Male', 18.0, 18.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 2000.0, 'Europe', 'High-income', 'Germany', 'Male', 20.0, 20.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 2012.0, 'Europe', 'High-income', 'Denmark', 'Both sexes', 80.0, 80.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 1990.0, 'Europe', 'High-income', 'Denmark', 'Male', 18.0, 18.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 2000.0, 'Europe', 'High-income', 'Denmark', 'Male', 19.0, 19.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 2000.0, 'Europe', 'High-income', 'Denmark', 'Both sexes', 21.0, 21.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 2012.0, 'Europe', 'High-income', 'Denmark', 'Both sexes', 23.0, 23.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 2012.0, 'Europe', 'High-income', 'Spain', 'Both sexes', 82.0, 82.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 2000.0, 'Europe', 'High-income', 'Spain', 'Female', 25.0, 25.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 1990.0, 'Europe', 'High-income', 'Spain', 'Both sexes', 22.0, 22.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 1990.0, 'Europe', 'High-income', 'Estonia', 'Female', 75.0, 75.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 2012.0, 'Europe', 'High-income', 'Estonia', 'Female', 81.0, 81.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 2012.0, 'Europe', 'High-income', 'Estonia', 'Male', 18.0, 18.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 2000.0, 'Europe', 'High-income', 'Estonia', 'Female', 21.0, 21.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 2012.0, 'Europe', 'High-income', 'Estonia', 'Female', 24.0, 24.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 1990.0, 'Europe', 'High-income', 'Finland', 'Female', 79.0, 79.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 2012.0, 'Europe', 'High-income', 'Finland', 'Male', 22.0, 22.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 2000.0, 'Europe', 'High-income', 'France', 'Male', 75.0, 75.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 2000.0, 'Europe', 'High-income', 'France', 'Male', 20.0, 20.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 2012.0, 'Europe', 'High-income', 'United Kingdom of Great Britain and Northern Ireland', 'Female', 83.0, 83.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 2012.0, 'Europe', 'High-income', 'United Kingdom of Great Britain and Northern Ireland', 'Both sexes', 81.0, 81.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 1990.0, 'Europe', 'High-income', 'United Kingdom of Great Britain and Northern Ireland', 'Male', 18.0, 18.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 2000.0, 'Africa', 'High-income', 'Equatorial Guinea', 'Female', 52.0, 52.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 1990.0, 'Africa', 'High-income', 'Equatorial Guinea', 'Female', 15.0, 15.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 2012.0, 'Africa', 'High-income', 'Equatorial Guinea', 'Female', 17.0, 17.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 2012.0, 'Europe', 'High-income', 'Greece', 'Male', 78.0, 78.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 2012.0, 'Europe', 'High-income', 'Greece', 'Female', 83.0, 83.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 2012.0, 'Europe', 'High-income', 'Croatia', 'Both sexes', 78.0, 78.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 1990.0, 'Europe', 'High-income', 'Croatia', 'Male', 16.0, 16.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 2000.0, 'Europe', 'High-income', 'Croatia', 'Both sexes', 19.0, 19.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 2000.0, 'Europe', 'High-income', 'Hungary', 'Male', 68.0, 68.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 2000.0, 'Europe', 'High-income', 'Hungary', 'Both sexes', 72.0, 72.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 1990.0, 'Europe', 'High-income', 'Hungary', 'Male', 15.0, 15.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 2012.0, 'Europe', 'High-income', 'Hungary', 'Female', 22.0, 22.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 2000.0, 'Europe', 'High-income', 'Hungary', 'Both sexes', 18.0, 18.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 2000.0, 'Europe', 'High-income', 'Ireland', 'Both sexes', 77.0, 77.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 1990.0, 'Europe', 'High-income', 'Ireland', 'Both sexes', 19.0, 19.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 2000.0, 'Europe', 'High-income', 'Ireland', 'Both sexes', 20.0, 20.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 2012.0, 'Europe', 'High-income', 'Iceland', 'Female', 84.0, 84.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 2000.0, 'Europe', 'High-income', 'Iceland', 'Female', 24.0, 24.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 1990.0, 'Europe', 'High-income', 'Israel', 'Male', 75.0, 75.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 2000.0, 'Europe', 'High-income', 'Israel', 'Male', 21.0, 21.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 2012.0, 'Europe', 'High-income', 'Israel', 'Both sexes', 24.0, 24.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 1990.0, 'Europe', 'High-income', 'Italy', 'Male', 74.0, 74.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 2000.0, 'Europe', 'High-income', 'Italy', 'Male', 77.0, 77.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 2000.0, 'Europe', 'High-income', 'Italy', 'Male', 21.0, 21.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 2012.0, 'Europe', 'High-income', 'Italy', 'Both sexes', 25.0, 25.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 2012.0, 'Western Pacific', 'High-income', 'Japan', 'Female', 29.0, 29.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 1990.0, 'Western Pacific', 'High-income', 'Japan', 'Both sexes', 23.0, 23.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 2000.0, 'Western Pacific', 'High-income', 'Japan', 'Both sexes', 25.0, 25.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 1990.0, 'Western Pacific', 'High-income', 'Republic of Korea', 'Female', 76.0, 76.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 1990.0, 'Western Pacific', 'High-income', 'Republic of Korea', 'Both sexes', 72.0, 72.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 2000.0, 'Western Pacific', 'High-income', 'Republic of Korea', 'Female', 23.0, 23.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 2000.0, 'Eastern Mediterranean', 'High-income', 'Kuwait', 'Male', 74.0, 74.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 2000.0, 'Eastern Mediterranean', 'High-income', 'Kuwait', 'Female', 76.0, 76.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 1990.0, 'Eastern Mediterranean', 'High-income', 'Kuwait', 'Female', 18.0, 18.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 2000.0, 'Europe', 'High-income', 'Luxembourg', 'Male', 75.0, 75.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 2012.0, 'Europe', 'High-income', 'Luxembourg', 'Both sexes', 82.0, 82.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 2000.0, 'Europe', 'High-income', 'Luxembourg', 'Male', 20.0, 20.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 2012.0, 'Europe', 'High-income', 'Luxembourg', 'Both sexes', 25.0, 25.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 2000.0, 'Europe', 'High-income', 'Monaco', 'Both sexes', 80.0, 80.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 2000.0, 'Europe', 'High-income', 'Monaco', 'Both sexes', 24.0, 24.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 1990.0, 'Europe', 'High-income', 'Malta', 'Female', 78.0, 78.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 2000.0, 'Europe', 'High-income', 'Malta', 'Female', 80.0, 80.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 1990.0, 'Europe', 'High-income', 'Malta', 'Both sexes', 76.0, 76.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 2000.0, 'Europe', 'High-income', 'Malta', 'Female', 23.0, 23.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 2000.0, 'Europe', 'High-income', 'Norway', 'Male', 76.0, 76.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 1990.0, 'Europe', 'High-income', 'Norway', 'Female', 80.0, 80.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 2000.0, 'Western Pacific', 'High-income', 'Nauru', 'Male', 73.0, 73.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 1990.0, 'Western Pacific', 'High-income', 'Nauru', 'Both sexes', 73.0, 73.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 2000.0, 'Western Pacific', 'High-income', 'Nauru', 'Both sexes', 77.0, 77.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 2012.0, 'Western Pacific', 'High-income', 'Nauru', 'Female', 27.0, 27.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 2000.0, 'Western Pacific', 'High-income', 'New Zealand', 'Both sexes', 79.0, 79.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 2000.0, 'Western Pacific', 'High-income', 'New Zealand', 'Female', 24.0, 24.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 2012.0, 'Eastern Mediterranean', 'High-income', 'Oman', 'Male', 74.0, 74.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 1990.0, 'Eastern Mediterranean', 'High-income', 'Oman', 'Female', 70.0, 70.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 2012.0, 'Eastern Mediterranean', 'High-income', 'Oman', 'Female', 78.0, 78.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 2000.0, 'Eastern Mediterranean', 'High-income', 'Oman', 'Male', 17.0, 17.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 1990.0, 'Eastern Mediterranean', 'High-income', 'Oman', 'Female', 18.0, 18.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 2012.0, 'Eastern Mediterranean', 'High-income', 'Oman', 'Female', 22.0, 22.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 2012.0, 'Europe', 'High-income', 'Portugal', 'Male', 22.0, 22.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 2012.0, 'Europe', 'High-income', 'Portugal', 'Both sexes', 24.0, 24.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 1990.0, 'Eastern Mediterranean', 'High-income', 'Qatar', 'Male', 74.0, 74.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 2000.0, 'Eastern Mediterranean', 'High-income', 'Qatar', 'Male', 77.0, 77.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 2000.0, 'Eastern Mediterranean', 'High-income', 'Qatar', 'Both sexes', 77.0, 77.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 2012.0, 'Eastern Mediterranean', 'High-income', 'Qatar', 'Both sexes', 22.0, 22.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 2000.0, 'Eastern Mediterranean', 'High-income', 'Saudi Arabia', 'Both sexes', 73.0, 73.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 2000.0, 'Europe', 'High-income', 'San Marino', 'Male', 78.0, 78.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 2012.0, 'Europe', 'High-income', 'San Marino', 'Male', 82.0, 82.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 2000.0, 'Europe', 'High-income', 'San Marino', 'Female', 85.0, 85.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 1990.0, 'Europe', 'High-income', 'San Marino', 'Male', 20.0, 20.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 2000.0, 'Europe', 'High-income', 'San Marino', 'Male', 22.0, 22.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 1990.0, 'Europe', 'High-income', 'San Marino', 'Female', 25.0, 25.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 1990.0, 'Europe', 'High-income', 'Slovakia', 'Male', 66.0, 66.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 2000.0, 'Europe', 'High-income', 'Slovakia', 'Both sexes', 73.0, 73.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 2012.0, 'Europe', 'High-income', 'Slovakia', 'Both sexes', 76.0, 76.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 1990.0, 'Europe', 'High-income', 'Slovenia', 'Male', 70.0, 70.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 2012.0, 'Europe', 'High-income', 'Slovenia', 'Female', 83.0, 83.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 1990.0, 'Europe', 'High-income', 'Slovenia', 'Both sexes', 74.0, 74.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 1990.0, 'Europe', 'High-income', 'Slovenia', 'Both sexes', 19.0, 19.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 2012.0, 'Europe', 'High-income', 'Slovenia', 'Both sexes', 23.0, 23.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 1990.0, 'Europe', 'High-income', 'Sweden', 'Both sexes', 78.0, 78.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 2012.0, 'Americas', 'High-income', 'Trinidad and Tobago', 'Male', 67.0, 67.0, '', '', '']
['Life expectancy at birth (years)', 'Published', 1990.0, 'Americas', 'High-income', 'Trinidad and Tobago', 'Female', 71.0, 71.0, '', '', '']
['Life expectancy at age 60 (years)', 'Published', 1990.0, 'Americas', 'High-income', 'Trinidad and Tobago', 'Female', 18.0, 18.0, '', '', '']